services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: smartparking-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: smartparking-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: smartparking-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://smartparking-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark:
    image: apache/spark:3.5.6
    container_name: smartparking-spark
    user: root
    depends_on:
      - kafka
      - cassandra
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null

  cassandra:
    image: cassandra:4.1
    container_name: smartparking-cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: SmartParkingCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1